package com.web.manager.area.entity;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_area.AREA_ID
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_area.AREA_NAME
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_area.CITY_ID
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_area.ORDERS
     *
     * @mbggenerated
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_area.IS_SHOW
     *
     * @mbggenerated
     */
    private Byte isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_area.AREA_ID
     *
     * @return the value of ts_area.AREA_ID
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_area.AREA_ID
     *
     * @param areaId the value for ts_area.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_area.AREA_NAME
     *
     * @return the value of ts_area.AREA_NAME
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_area.AREA_NAME
     *
     * @param areaName the value for ts_area.AREA_NAME
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_area.CITY_ID
     *
     * @return the value of ts_area.CITY_ID
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_area.CITY_ID
     *
     * @param cityId the value for ts_area.CITY_ID
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_area.ORDERS
     *
     * @return the value of ts_area.ORDERS
     *
     * @mbggenerated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_area.ORDERS
     *
     * @param orders the value for ts_area.ORDERS
     *
     * @mbggenerated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_area.IS_SHOW
     *
     * @return the value of ts_area.IS_SHOW
     *
     * @mbggenerated
     */
    public Byte getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_area.IS_SHOW
     *
     * @param isShow the value for ts_area.IS_SHOW
     *
     * @mbggenerated
     */
    public void setIsShow(Byte isShow) {
        this.isShow = isShow;
    }
}