package com.web.applications.article.entity;

public class ArticleType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_type.ARTICLE_TYPE_ID
     *
     * @mbggenerated
     */
    private String articleTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_type.ARTICLE_ID
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_type.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_type.ARTICLE_TYPE_ID
     *
     * @return the value of tb_article_type.ARTICLE_TYPE_ID
     *
     * @mbggenerated
     */
    public String getArticleTypeId() {
        return articleTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_type.ARTICLE_TYPE_ID
     *
     * @param articleTypeId the value for tb_article_type.ARTICLE_TYPE_ID
     *
     * @mbggenerated
     */
    public void setArticleTypeId(String articleTypeId) {
        this.articleTypeId = articleTypeId == null ? null : articleTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_type.ARTICLE_ID
     *
     * @return the value of tb_article_type.ARTICLE_ID
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_type.ARTICLE_ID
     *
     * @param articleId the value for tb_article_type.ARTICLE_ID
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_type.TYPE_ID
     *
     * @return the value of tb_article_type.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_type.TYPE_ID
     *
     * @param typeId the value for tb_article_type.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }
}