package com.web.applications.article.entity;

public class ArticleWithBLOBs extends Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_BODY
     *
     * @mbggenerated
     */
    private String articleBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_DESCRIPTION
     *
     * @mbggenerated
     */
    private String articleDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_BODY
     *
     * @return the value of tb_article.ARTICLE_BODY
     *
     * @mbggenerated
     */
    public String getArticleBody() {
        return articleBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_BODY
     *
     * @param articleBody the value for tb_article.ARTICLE_BODY
     *
     * @mbggenerated
     */
    public void setArticleBody(String articleBody) {
        this.articleBody = articleBody == null ? null : articleBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_DESCRIPTION
     *
     * @return the value of tb_article.ARTICLE_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getArticleDescription() {
        return articleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_DESCRIPTION
     *
     * @param articleDescription the value for tb_article.ARTICLE_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setArticleDescription(String articleDescription) {
        this.articleDescription = articleDescription == null ? null : articleDescription.trim();
    }
}