package com.web.applications.article.entity;

import java.util.Date;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_SID
     *
     * @mbggenerated
     */
    private Integer articleSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_ID
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_TITLE
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_BACKUP1
     *
     * @mbggenerated
     */
    private String articleBackup1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_BACKUP2
     *
     * @mbggenerated
     */
    private String articleBackup2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_BACKUP3
     *
     * @mbggenerated
     */
    private String articleBackup3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article.ARTICLE_IMG
     *
     * @mbggenerated
     */
    private String articleImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_SID
     *
     * @return the value of tb_article.ARTICLE_SID
     *
     * @mbggenerated
     */
    public Integer getArticleSid() {
        return articleSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_SID
     *
     * @param articleSid the value for tb_article.ARTICLE_SID
     *
     * @mbggenerated
     */
    public void setArticleSid(Integer articleSid) {
        this.articleSid = articleSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_ID
     *
     * @return the value of tb_article.ARTICLE_ID
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_ID
     *
     * @param articleId the value for tb_article.ARTICLE_ID
     *
     * @mbggenerated
     */
    public void setArticleId(String articleId) {
        this.articleId = articleId == null ? null : articleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.CREATE_DATE
     *
     * @return the value of tb_article.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.CREATE_DATE
     *
     * @param createDate the value for tb_article.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.UPDATE_DATE
     *
     * @return the value of tb_article.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.UPDATE_DATE
     *
     * @param updateDate the value for tb_article.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_TITLE
     *
     * @return the value of tb_article.ARTICLE_TITLE
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_TITLE
     *
     * @param articleTitle the value for tb_article.ARTICLE_TITLE
     *
     * @mbggenerated
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_BACKUP1
     *
     * @return the value of tb_article.ARTICLE_BACKUP1
     *
     * @mbggenerated
     */
    public String getArticleBackup1() {
        return articleBackup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_BACKUP1
     *
     * @param articleBackup1 the value for tb_article.ARTICLE_BACKUP1
     *
     * @mbggenerated
     */
    public void setArticleBackup1(String articleBackup1) {
        this.articleBackup1 = articleBackup1 == null ? null : articleBackup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_BACKUP2
     *
     * @return the value of tb_article.ARTICLE_BACKUP2
     *
     * @mbggenerated
     */
    public String getArticleBackup2() {
        return articleBackup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_BACKUP2
     *
     * @param articleBackup2 the value for tb_article.ARTICLE_BACKUP2
     *
     * @mbggenerated
     */
    public void setArticleBackup2(String articleBackup2) {
        this.articleBackup2 = articleBackup2 == null ? null : articleBackup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_BACKUP3
     *
     * @return the value of tb_article.ARTICLE_BACKUP3
     *
     * @mbggenerated
     */
    public String getArticleBackup3() {
        return articleBackup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_BACKUP3
     *
     * @param articleBackup3 the value for tb_article.ARTICLE_BACKUP3
     *
     * @mbggenerated
     */
    public void setArticleBackup3(String articleBackup3) {
        this.articleBackup3 = articleBackup3 == null ? null : articleBackup3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article.ARTICLE_IMG
     *
     * @return the value of tb_article.ARTICLE_IMG
     *
     * @mbggenerated
     */
    public String getArticleImg() {
        return articleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article.ARTICLE_IMG
     *
     * @param articleImg the value for tb_article.ARTICLE_IMG
     *
     * @mbggenerated
     */
    public void setArticleImg(String articleImg) {
        this.articleImg = articleImg == null ? null : articleImg.trim();
    }
}