package com.web.applications.article.entity;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.TYPE_SID
     *
     * @mbggenerated
     */
    private Integer typeSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.TYPE_NAME
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_type.TYPE_PARENT_ID
     *
     * @mbggenerated
     */
    private String typeParentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.TYPE_SID
     *
     * @return the value of tb_type.TYPE_SID
     *
     * @mbggenerated
     */
    public Integer getTypeSid() {
        return typeSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.TYPE_SID
     *
     * @param typeSid the value for tb_type.TYPE_SID
     *
     * @mbggenerated
     */
    public void setTypeSid(Integer typeSid) {
        this.typeSid = typeSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.TYPE_ID
     *
     * @return the value of tb_type.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.TYPE_ID
     *
     * @param typeId the value for tb_type.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.TYPE_NAME
     *
     * @return the value of tb_type.TYPE_NAME
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.TYPE_NAME
     *
     * @param typeName the value for tb_type.TYPE_NAME
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_type.TYPE_PARENT_ID
     *
     * @return the value of tb_type.TYPE_PARENT_ID
     *
     * @mbggenerated
     */
    public String getTypeParentId() {
        return typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_type.TYPE_PARENT_ID
     *
     * @param typeParentId the value for tb_type.TYPE_PARENT_ID
     *
     * @mbggenerated
     */
    public void setTypeParentId(String typeParentId) {
        this.typeParentId = typeParentId == null ? null : typeParentId.trim();
    }
}