package com.web.applications.article.dao;

import com.system.webui.Page;
import com.web.applications.article.entity.ArticleType;

import java.util.List;

public interface ArticleTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String articleTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_type
     *
     * @mbggenerated
     */
    int insert(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_type
     *
     * @mbggenerated
     */
    int insertSelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_type
     *
     * @mbggenerated
     */
    ArticleType selectByPrimaryKey(String articleTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArticleType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArticleType record);

    List<ArticleType> selectByPage(Page<ArticleType> page);

    Integer getCounts(Page<ArticleType> page);
}