package com.web.applications.article.dao;

import com.system.webui.Page;
import com.system.webui.Tree;
import com.web.applications.article.entity.Type;

import java.util.List;
import java.util.Map;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer typeSid);

    int deleteByPrimaryId(String typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbggenerated
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbggenerated
     */
    int insertSelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbggenerated
     */
    Type selectByPrimaryKey(Integer typeSid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Type record);

    List<Type> selectByPage(Page<Type> page);

    Integer getCounts(Page<Type> page);

    List<Tree> selectTree(Map<String, Object> map);

    List<Tree> selectToTree();

}