package com.web.manager.city.entity;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_city.CITY_ID
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_city.CITY_NAME
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_city.PROVINCE_ID
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_city.ORDERS
     *
     * @mbggenerated
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_city.IS_SHOW
     *
     * @mbggenerated
     */
    private Byte isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_city.CITY_ID
     *
     * @return the value of ts_city.CITY_ID
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_city.CITY_ID
     *
     * @param cityId the value for ts_city.CITY_ID
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_city.CITY_NAME
     *
     * @return the value of ts_city.CITY_NAME
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_city.CITY_NAME
     *
     * @param cityName the value for ts_city.CITY_NAME
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_city.PROVINCE_ID
     *
     * @return the value of ts_city.PROVINCE_ID
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_city.PROVINCE_ID
     *
     * @param provinceId the value for ts_city.PROVINCE_ID
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_city.ORDERS
     *
     * @return the value of ts_city.ORDERS
     *
     * @mbggenerated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_city.ORDERS
     *
     * @param orders the value for ts_city.ORDERS
     *
     * @mbggenerated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_city.IS_SHOW
     *
     * @return the value of ts_city.IS_SHOW
     *
     * @mbggenerated
     */
    public Byte getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_city.IS_SHOW
     *
     * @param isShow the value for ts_city.IS_SHOW
     *
     * @mbggenerated
     */
    public void setIsShow(Byte isShow) {
        this.isShow = isShow;
    }
}