package com.web.manager.role.dao;


import com.web.manager.role.entity.RoleResource;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbggenerated
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbggenerated
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbggenerated
     */
    RoleResource selectByPrimaryKey(String roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_role_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleResource record);
    
}