package com.web.manager.province.entity;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_province.PROVINCE_ID
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_province.PROVINCE_NAME
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_province.ORDER
     *
     * @mbggenerated
     */
    private Integer order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_province.IS_SHOW
     *
     * @mbggenerated
     */
    private Byte isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_province.PROVINCE_ID
     *
     * @return the value of ts_province.PROVINCE_ID
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_province.PROVINCE_ID
     *
     * @param provinceId the value for ts_province.PROVINCE_ID
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_province.PROVINCE_NAME
     *
     * @return the value of ts_province.PROVINCE_NAME
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_province.PROVINCE_NAME
     *
     * @param provinceName the value for ts_province.PROVINCE_NAME
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_province.ORDER
     *
     * @return the value of ts_province.ORDER
     *
     * @mbggenerated
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_province.ORDER
     *
     * @param order the value for ts_province.ORDER
     *
     * @mbggenerated
     */
    public void setOrder(Integer order) {
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_province.IS_SHOW
     *
     * @return the value of ts_province.IS_SHOW
     *
     * @mbggenerated
     */
    public Byte getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_province.IS_SHOW
     *
     * @param isShow the value for ts_province.IS_SHOW
     *
     * @mbggenerated
     */
    public void setIsShow(Byte isShow) {
        this.isShow = isShow;
    }
}