package com.web.manager.user.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.USER_PASSWORD
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.LAST_LOGIN_DATE
     *
     * @mbggenerated
     */
    private Date lastLoginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.IS_LOCK
     *
     * @mbggenerated
     */
    private Boolean isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.IS_DELETE
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.ERR_PASSWORD_TIME
     *
     * @mbggenerated
     */
    private Integer errPasswordTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.PROVINCE_ID
     *
     * @mbggenerated
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.CITY_ID
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.AREA_ID
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.USER_PHONE
     *
     * @mbggenerated
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.USER_NICK
     *
     * @mbggenerated
     */
    private String userNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user.ERR_PASSWORD_LOCK_TIME
     *
     * @mbggenerated
     */
    private Date errPasswordLockTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.USER_ID
     *
     * @return the value of ts_user.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.USER_ID
     *
     * @param userId the value for ts_user.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.USER_NAME
     *
     * @return the value of ts_user.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.USER_NAME
     *
     * @param userName the value for ts_user.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.USER_PASSWORD
     *
     * @return the value of ts_user.USER_PASSWORD
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.USER_PASSWORD
     *
     * @param userPassword the value for ts_user.USER_PASSWORD
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.CREATE_DATE
     *
     * @return the value of ts_user.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.CREATE_DATE
     *
     * @param createDate the value for ts_user.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.UPDATE_DATE
     *
     * @return the value of ts_user.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.UPDATE_DATE
     *
     * @param updateDate the value for ts_user.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.LAST_LOGIN_DATE
     *
     * @return the value of ts_user.LAST_LOGIN_DATE
     *
     * @mbggenerated
     */
    public Date getLastLoginDate() {
        return lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.LAST_LOGIN_DATE
     *
     * @param lastLoginDate the value for ts_user.LAST_LOGIN_DATE
     *
     * @mbggenerated
     */
    public void setLastLoginDate(Date lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.IS_LOCK
     *
     * @return the value of ts_user.IS_LOCK
     *
     * @mbggenerated
     */
    public Boolean getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.IS_LOCK
     *
     * @param isLock the value for ts_user.IS_LOCK
     *
     * @mbggenerated
     */
    public void setIsLock(Boolean isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.IS_DELETE
     *
     * @return the value of ts_user.IS_DELETE
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.IS_DELETE
     *
     * @param isDelete the value for ts_user.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.ERR_PASSWORD_TIME
     *
     * @return the value of ts_user.ERR_PASSWORD_TIME
     *
     * @mbggenerated
     */
    public Integer getErrPasswordTime() {
        return errPasswordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.ERR_PASSWORD_TIME
     *
     * @param errPasswordTime the value for ts_user.ERR_PASSWORD_TIME
     *
     * @mbggenerated
     */
    public void setErrPasswordTime(Integer errPasswordTime) {
        this.errPasswordTime = errPasswordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.PROVINCE_ID
     *
     * @return the value of ts_user.PROVINCE_ID
     *
     * @mbggenerated
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.PROVINCE_ID
     *
     * @param provinceId the value for ts_user.PROVINCE_ID
     *
     * @mbggenerated
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.CITY_ID
     *
     * @return the value of ts_user.CITY_ID
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.CITY_ID
     *
     * @param cityId the value for ts_user.CITY_ID
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.AREA_ID
     *
     * @return the value of ts_user.AREA_ID
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.AREA_ID
     *
     * @param areaId the value for ts_user.AREA_ID
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.ADDRESS
     *
     * @return the value of ts_user.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.ADDRESS
     *
     * @param address the value for ts_user.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.USER_PHONE
     *
     * @return the value of ts_user.USER_PHONE
     *
     * @mbggenerated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.USER_PHONE
     *
     * @param userPhone the value for ts_user.USER_PHONE
     *
     * @mbggenerated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.USER_NICK
     *
     * @return the value of ts_user.USER_NICK
     *
     * @mbggenerated
     */
    public String getUserNick() {
        return userNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.USER_NICK
     *
     * @param userNick the value for ts_user.USER_NICK
     *
     * @mbggenerated
     */
    public void setUserNick(String userNick) {
        this.userNick = userNick == null ? null : userNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user.ERR_PASSWORD_LOCK_TIME
     *
     * @return the value of ts_user.ERR_PASSWORD_LOCK_TIME
     *
     * @mbggenerated
     */
    public Date getErrPasswordLockTime() {
        return errPasswordLockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user.ERR_PASSWORD_LOCK_TIME
     *
     * @param errPasswordLockTime the value for ts_user.ERR_PASSWORD_LOCK_TIME
     *
     * @mbggenerated
     */
    public void setErrPasswordLockTime(Date errPasswordLockTime) {
        this.errPasswordLockTime = errPasswordLockTime;
    }
}