package com.web.manager.user.entity;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user_role.USER_ROLE_ID
     *
     * @mbggenerated
     */
    private String userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user_role.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user_role.ROLE_DESCRIPTION
     *
     * @mbggenerated
     */
    private String roleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_user_role.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user_role.USER_ROLE_ID
     *
     * @return the value of ts_user_role.USER_ROLE_ID
     *
     * @mbggenerated
     */
    public String getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user_role.USER_ROLE_ID
     *
     * @param userRoleId the value for ts_user_role.USER_ROLE_ID
     *
     * @mbggenerated
     */
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId == null ? null : userRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user_role.USER_ID
     *
     * @return the value of ts_user_role.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user_role.USER_ID
     *
     * @param userId the value for ts_user_role.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user_role.ROLE_DESCRIPTION
     *
     * @return the value of ts_user_role.ROLE_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user_role.ROLE_DESCRIPTION
     *
     * @param roleDescription the value for ts_user_role.ROLE_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_user_role.ROLE_ID
     *
     * @return the value of ts_user_role.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_user_role.ROLE_ID
     *
     * @param roleId the value for ts_user_role.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}