package com.web.manager.role.entity;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.ROLE_DESCRIPTION
     *
     * @mbggenerated
     */
    private String roleDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.ROLE_TYPE1
     *
     * @mbggenerated
     */
    private String roleType1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.ROLE_TYPE2
     *
     * @mbggenerated
     */
    private String roleType2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.IS_DELETE
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role.ROLE_SHIRO
     *
     * @mbggenerated
     */
    private String roleShiro;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.ROLE_ID
     *
     * @return the value of ts_role.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.ROLE_ID
     *
     * @param roleId the value for ts_role.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.ROLE_NAME
     *
     * @return the value of ts_role.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.ROLE_NAME
     *
     * @param roleName the value for ts_role.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.ROLE_DESCRIPTION
     *
     * @return the value of ts_role.ROLE_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getRoleDescription() {
        return roleDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.ROLE_DESCRIPTION
     *
     * @param roleDescription the value for ts_role.ROLE_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setRoleDescription(String roleDescription) {
        this.roleDescription = roleDescription == null ? null : roleDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.ROLE_TYPE1
     *
     * @return the value of ts_role.ROLE_TYPE1
     *
     * @mbggenerated
     */
    public String getRoleType1() {
        return roleType1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.ROLE_TYPE1
     *
     * @param roleType1 the value for ts_role.ROLE_TYPE1
     *
     * @mbggenerated
     */
    public void setRoleType1(String roleType1) {
        this.roleType1 = roleType1 == null ? null : roleType1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.ROLE_TYPE2
     *
     * @return the value of ts_role.ROLE_TYPE2
     *
     * @mbggenerated
     */
    public String getRoleType2() {
        return roleType2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.ROLE_TYPE2
     *
     * @param roleType2 the value for ts_role.ROLE_TYPE2
     *
     * @mbggenerated
     */
    public void setRoleType2(String roleType2) {
        this.roleType2 = roleType2 == null ? null : roleType2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.CREATE_DATE
     *
     * @return the value of ts_role.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.CREATE_DATE
     *
     * @param createDate the value for ts_role.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.UPDATE_DATE
     *
     * @return the value of ts_role.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.UPDATE_DATE
     *
     * @param updateDate the value for ts_role.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.IS_DELETE
     *
     * @return the value of ts_role.IS_DELETE
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.IS_DELETE
     *
     * @param isDelete the value for ts_role.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role.ROLE_SHIRO
     *
     * @return the value of ts_role.ROLE_SHIRO
     *
     * @mbggenerated
     */
    public String getRoleShiro() {
        return roleShiro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role.ROLE_SHIRO
     *
     * @param roleShiro the value for ts_role.ROLE_SHIRO
     *
     * @mbggenerated
     */
    public void setRoleShiro(String roleShiro) {
        this.roleShiro = roleShiro == null ? null : roleShiro.trim();
    }
}