package com.web.manager.role.entity;

public class RoleResource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role_resource.ROLE_RESOURCE_ID
     *
     * @mbggenerated
     */
    private String roleResourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role_resource.ROLE_ID
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_role_resource.RESOURCE_ID
     *
     * @mbggenerated
     */
    private String resourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role_resource.ROLE_RESOURCE_ID
     *
     * @return the value of ts_role_resource.ROLE_RESOURCE_ID
     *
     * @mbggenerated
     */
    public String getRoleResourceId() {
        return roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role_resource.ROLE_RESOURCE_ID
     *
     * @param roleResourceId the value for ts_role_resource.ROLE_RESOURCE_ID
     *
     * @mbggenerated
     */
    public void setRoleResourceId(String roleResourceId) {
        this.roleResourceId = roleResourceId == null ? null : roleResourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role_resource.ROLE_ID
     *
     * @return the value of ts_role_resource.ROLE_ID
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role_resource.ROLE_ID
     *
     * @param roleId the value for ts_role_resource.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_role_resource.RESOURCE_ID
     *
     * @return the value of ts_role_resource.RESOURCE_ID
     *
     * @mbggenerated
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_role_resource.RESOURCE_ID
     *
     * @param resourceId the value for ts_role_resource.RESOURCE_ID
     *
     * @mbggenerated
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }
}