package com.web.manager.resource.dao;

import java.util.List;
import java.util.Map;

import com.web.manager.resource.entity.Resource;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resources
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resources
     *
     * @mbggenerated
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resources
     *
     * @mbggenerated
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resources
     *
     * @mbggenerated
     */
    Resource selectByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resources
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_resources
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Resource record);
    
    List<Resource> selectAllResources();
    
    List<Resource> selectResourceByMap(Map<String, Object> map);
}